modLoader="javafml"
loaderVersion="[38,)"
license="ARR"

[[mods]]
modId="lychee"
version="${file.jarVersion}"
displayName="Lychee Tweaker"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lychee"
description="In-World Crafting"

[[dependencies.lychee]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[modproperties.lychee]
    catalogueItemIcon="minecraft:snow_block" #Support for Catalogue mod
